import { Playfair_Display, Dancing_Script } from "next/font/google";
import CursorDot from "@/components/ui/CursorDot";
import IntroAnimation from "@/components/ui/IntroAnimation";
import { DEFAULT_METADATA, VIEWPORT, PERSON_SCHEMA } from "@/constants/seo";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// import { Playfair_Display } from "next/font/google";
// const playfair = Playfair_Display({ subsets: ["latin"], weight: ["700"] });
// import { Playfair_Display } from "next/font/google";
// import IntroAnimation from "@/components/ui/IntroAnimation";

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-playfair",
});

const dancing = Dancing_Script({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-dancing",
});

const BASE_URL = "https://avyuktrobolap.com"; // 🔁 change to actual domain

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata = {
  metadataBase: new URL(BASE_URL),
  title: {
    default: "Dr. Abhishek Jaimalani | Robotic & Laparoscopic Surgeon – Surat",
    template: "%s | Dr. Abhishek Jaimalani",
  },
  description:
    "Dr. Abhishek Jaimalani is a specialist in robotic and laparoscopic surgery at Avyukt Robolap, Surat. Advanced minimally invasive procedures with precision and care.",
  keywords: [
    "Dr Abhishek Jaimalani",
    "Avyukt Robolap",
    "robotic surgery Surat",
    "laparoscopic surgeon Surat",
    "minimally invasive surgery Gujarat",
  ],
  openGraph: {
    title: "Dr. Abhishek Jaimalani | Robotic & Laparoscopic Surgeon – Surat",
    description:
      "Advanced robotic and laparoscopic surgery in Surat. Book a consultation with Dr. Abhishek Jaimalani at Avyukt Robolap.",
    url: BASE_URL,
    siteName: "Avyukt Robolap",
    type: "website",
    images: [
      {
        url: "/og-image.jpg",
        width: 1200,
        height: 630,
        alt: "Dr. Abhishek Jaimalani – Avyukt Robolap",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Dr. Abhishek Jaimalani | Robotic Surgeon – Surat",
    description: "Robotic & laparoscopic surgery specialist in Surat, Gujarat.",
    images: ["/og-image.jpg"],
  },
  alternates: {
    canonical: BASE_URL,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true },
  },
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/apple-icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${playfair.variable} ${dancing.variable}`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <IntroAnimation />
        <CursorDot />
        {children}
      </body>
    </html>
  );
}
